export enum EnvVar {
  NODE_ENV = 'NODE_ENV',
  MONGO_CONNECTION_URI = 'MONGO_CONNECTION_URI',
  SERVER_BASE_URL = 'SERVER_BASE_URL',
  SERVER_JWT_SECRET = 'SERVER_JWT_SECRET',
  SERVER_PORT = 'SERVER_PORT',
  SERVER_SESSION_SECRET = 'SERVER_SESSION_SECRET',
  TIKTOK_CLIENT_KEY = 'TIKTOK_CLIENT_KEY',
  TIKTOK_CLIENT_SECRET = 'TIKTOK_CLIENT_SECRET',
}
